### PR TITLE
Add devtools-kubernetes-v1beta1

### PR DESCRIPTION
**Pull request by drakenator**
Dusted this off from dugnad day and added some tests. Supports validation via a simple kustomize parsing check as well as kubeval, kube-score.

Tested with hello-world infrastructure, and a few other projects we have where validation successfully detects improvements to be made.

### CODE REVIEW

**Review by aucampia — APPROVED** [review]
Thanks @drakenator looks pretty good.

**Comment by AtzeDeVries** [comment]
can we maybe use kubeconform instead of kubeval? Kubeval does not properly support validating CRD's (like istio etc) but kubeconform does. For implementation check the kubernetes workflow.  

https://github.com/coopnorge/github-workflow-kubernetes-validation/blob/main/.github/workflows/kubernetes-validation.yaml#L56-L58

https://github.com/coopnorge/github-workflow-kubernetes-validation/blob/main/.github/workflows/kubernetes-validation.yaml#L76-L83

**Comment by AtzeDeVries** [comment]
second thing is, the why of adding kubectl, we could also just add kustomize. Kubectl is 45MB and the kustomize bin is just 7MB. It depends a bit on where we want to go, but for CI, i guess kubectl is not really required, unless you want to do diffs to cluster using kubectl, but i generally prefer the argocd path.

**Comment by aucampia** [comment]
> can we maybe use kubeconform instead of kubeval? Kubeval does not properly support validating CRD's (like istio etc) but kubeconform does. For implementation check the kubernetes workflow.

I'm happy to change this in future but would rather have kubeval than nothing, and at the moment we are faced with a choice, copy more boilerplate to do local validation or have nothing.

**Comment by aucampia** [comment]
> second thing is, the why of adding kubectl, we could also just add kustomize. Kubectl is 45MB and the kustomize bin is just 7MB. It depends a bit on where we want to go, but for CI, i guess kubectl is not really required, unless you want to do diffs to cluster using kubectl, but i generally prefer the argocd path.

Probably we don't need it if going with ArgoCD, which we should, many things that are still on AZDO is not using ArgoCD though, and I also think it may be useful for checking cluster status and config while developing, which is something these images should also be useful and used for as they are also intended as developer tools.

I can live without it though, but again I would rather have something imperfect than nothing or more boilerplate.

**Review by aucampia — APPROVED** [review]
@drakenator just a reminder on this, I would merge if I were you, I think @AtzeDeVries has good points but if we merge this there is something for others to start on when they want to make those changes.

**Comment by drakenator** [comment]
I put this together mostly looking at what the AZDO projects were doing. I added kubct as it was used for misc stuff there. Won't have time to look into other things right now, so I'll merge it so long so that there is at least something usable by some projects Can pick this up again at the next Dugnad day.

**Pull request merged**
